/**
 * gen-sw.mjs — scans public/ and emits public/sw.js with a versioned precache
 * list. Run with: node scripts/gen-sw.mjs
 */
import { readdirSync, writeFileSync, statSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "public");

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

const assets = walk(root)
  .map((p) => "/" + relative(root, p).split(join("/")).join("/"))
  .filter((u) => u !== "/sw.js")
  // remote fixtures represent the network — never precached
  .filter((u) => !u.startsWith("/data/remote"))
  .sort();

const version = "v" + Date.now();
const sw = `// GENERATED by scripts/gen-sw.mjs — do not edit by hand.
const CACHE = "linye-${version}";
const PRECACHE = ${JSON.stringify(assets, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Station fixtures live "on the network": never serve them from cache, so
  // the sync desk's failure/retry behaviour is real while offline.
  if (url.pathname.startsWith("/data/remote")) {
    event.respondWith(fetch(req));
    return;
  }

  // App shell + media: cache-first, refresh cache in the background.
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      const network = fetch(req)
        .then((res) => {
          if (res && res.status === 200) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => hit);
      return hit || network;
    })
  );
});
`;

writeFileSync(join(root, "sw.js"), sw);
console.log(`sw.js written with ${assets.length} assets (${version})`);
